"use client"
export const jobTypes = ['Remote', 'Hybrid', 'Office', 'Other'];
export const genderPreferences = ['Male', 'Female', 'Any'];
export const workingDaysOptions = ['5 Days', '6 Days', 'Other'];
export const experiences = ['Freshers', '0-6 months', '0-1 year', '0-2 year', '1-2 year', '3 year', '2-5 year', '5+ year']
export const joining = ['Immediate', '1 week', '10 days', '15 days', '30 days', '45 days', '60 days', '90 days']
export const industryType = [
    "Information Technology",
    "Healthcare",
    "Finance",
    "Manufacturing",
    "Retail",
    "Education",
    "Construction",
    "Real Estate",
    "Telecommunications",
    "Automotive",
    "Aerospace",
    "Agriculture",
    "Hospitality",
    "Food and Beverage",
    "Entertainment",
    "Media and Publishing",
    "Pharmaceuticals",
    "Energy and Utilities",
    "Government and Public Sector",
    "Logistics and Transportation",
    "Insurance",
    "Legal Services",
    "Consulting",
    "Marketing and Advertising",
    "Fashion and Apparel",
    "Biotechnology",
    "Chemicals",
    "Mining and Metals",
    "Nonprofit",
    "Environmental Services",
    "Sports and Recreation",
    "Textile Industry",
    "Consumer Goods",
    "E-Commerce",
    "Architecture and Design",
    "Human Resources",
    "Research and Development",
    "Arts and Culture",
    "Security",
    "Event Management",
    "Gaming",
    "Tourism",
    "Petroleum and Natural Gas",
    "Robotics",
    "Nanotechnology",
    "Data Science and Analytics",
    "Blockchain and Cryptocurrency",
    "Marine and Shipping",
    "Social Media",
    "Electronics",
    "Defense and Military"
];
export const employmentTypes = [
    'Permanent',
    'Contract',
    'Internship',
    'Part-time',
    'Freelance',
    'Temporary',
    'Volunteer',
    'Seasonal',
  ];